---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-chatbot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ansible-chatbot-server-env-properties
immutable: false
data:
  ANSIBLE_CHATBOT_IMAGE_TAG: "aap-0.2.9"
  INFERENCE_MODEL: "granite-3.3-8b-instruct"
  LLAMA_STACK_PORT: '8321'
  # TODO: Use Secrets instead.
  VLLM_API_TOKEN: ""
  # TODO: Use Secrets instead.
  VLLM_URL: ''
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-chatbot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ansible-chatbot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ansible-chatbot
    spec:
      imagePullSecrets:
      - name: quay-pull-secret
      containers:
      - name: ansible-chatbot
        # TODO: Just using a temporal container. Change it to the final one, with access controls.
        image: ansible-chatbot:aap-0.2.9
        imagePullPolicy: IfNotPresent
        env:
          - name: LLAMA_STACK_CONFIG_DIR
            value: /.llama/data/
        envFrom:
          - configMapRef:
              name: "ansible-chatbot-server-env-properties"
        ports:
          - containerPort: 8321
        volumeMounts:
          - name: ansible-chatbot-storage
            mountPath: /.llama/data
      volumes:
      - name: ansible-chatbot-storage
        persistentVolumeClaim:
          claimName: ansible-chatbot-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ansible-chatbot-service
spec:
  selector:
    app.kubernetes.io/name: ansible-chatbot
  ports:
  - protocol: TCP
    port: 8321
    targetPort: 8321
  type: ClusterIP
